"""add group buying pool tables

Revision ID: 0cc0e18d4fcc
Revises: d9ba1837e850
Create Date: 2026-09-20 18:56:26.148175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cc0e18d4fcc'
down_revision: Union[str, None] = 'd9ba1837e850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buying_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('closes_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buying_pool_code'), 'buying_pool', ['code'], unique=True)
    op.create_index(op.f('ix_buying_pool_status'), 'buying_pool', ['status'], unique=False)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_code'), 'supplier', ['code'], unique=True)
    op.create_table('pool_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['buying_pool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_event_kind'), 'pool_event', ['kind'], unique=False)
    op.create_index(op.f('ix_pool_event_pool_id'), 'pool_event', ['pool_id'], unique=False)
    op.create_table('pool_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['buying_pool.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_order_pool_id'), 'pool_order', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_order_sku'), 'pool_order', ['sku'], unique=False)
    op.create_index(op.f('ix_pool_order_store_id'), 'pool_order', ['store_id'], unique=False)
    op.create_table('pool_settlement_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price_list_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_alone', sa.Integer(), nullable=False),
    sa.Column('payable', sa.Integer(), nullable=False),
    sa.Column('savings', sa.Integer(), nullable=False),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['buying_pool.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_settlement_line_pool_id'), 'pool_settlement_line', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_settlement_line_store_id'), 'pool_settlement_line', ['store_id'], unique=False)
    op.create_table('price_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_list_sku'), 'price_list', ['sku'], unique=False)
    op.create_index(op.f('ix_price_list_supplier_id'), 'price_list', ['supplier_id'], unique=False)
    op.create_table('pool_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['buying_pool.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_product_pool_id'), 'pool_product', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_product_sku'), 'pool_product', ['sku'], unique=False)
    op.create_table('price_tier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('max_qty', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_tier_price_list_id'), 'price_tier', ['price_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_tier_price_list_id'), table_name='price_tier')
    op.drop_table('price_tier')
    op.drop_index(op.f('ix_pool_product_sku'), table_name='pool_product')
    op.drop_index(op.f('ix_pool_product_pool_id'), table_name='pool_product')
    op.drop_table('pool_product')
    op.drop_index(op.f('ix_price_list_supplier_id'), table_name='price_list')
    op.drop_index(op.f('ix_price_list_sku'), table_name='price_list')
    op.drop_table('price_list')
    op.drop_index(op.f('ix_pool_settlement_line_store_id'), table_name='pool_settlement_line')
    op.drop_index(op.f('ix_pool_settlement_line_pool_id'), table_name='pool_settlement_line')
    op.drop_table('pool_settlement_line')
    op.drop_index(op.f('ix_pool_order_store_id'), table_name='pool_order')
    op.drop_index(op.f('ix_pool_order_sku'), table_name='pool_order')
    op.drop_index(op.f('ix_pool_order_pool_id'), table_name='pool_order')
    op.drop_table('pool_order')
    op.drop_index(op.f('ix_pool_event_pool_id'), table_name='pool_event')
    op.drop_index(op.f('ix_pool_event_kind'), table_name='pool_event')
    op.drop_table('pool_event')
    op.drop_index(op.f('ix_supplier_code'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_buying_pool_status'), table_name='buying_pool')
    op.drop_index(op.f('ix_buying_pool_code'), table_name='buying_pool')
    op.drop_table('buying_pool')
    # ### end Alembic commands ###
