"""add feature 2 tables

Revision ID: d9ba1837e850
Revises: d48a5ea7aaf8
Create Date: 2026-09-19 13:19:42.960918

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ba1837e850'
down_revision: Union[str, None] = 'd48a5ea7aaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku_a', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku_b', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transactions_with_both', sa.Integer(), nullable=False),
    sa.Column('transactions_with_a', sa.Integer(), nullable=False),
    sa.Column('transactions_with_b', sa.Integer(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lift', sa.Float(), nullable=False),
    sa.Column('separate_price', sa.Float(), nullable=False),
    sa.Column('separate_cost', sa.Float(), nullable=False),
    sa.Column('suggested_price', sa.Float(), nullable=False),
    sa.Column('suggested_margin_pct', sa.Float(), nullable=False),
    sa.Column('margin_floor_pct', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_suggestion_store_id'), 'bundle_suggestion', ['store_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=False)
    op.create_index(op.f('ix_product_store_id'), 'product', ['store_id'], unique=False)
    op.create_table('sale_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_line_date'), 'sale_line', ['date'], unique=False)
    op.create_index(op.f('ix_sale_line_sku'), 'sale_line', ['sku'], unique=False)
    op.create_index(op.f('ix_sale_line_store_id'), 'sale_line', ['store_id'], unique=False)
    op.create_index(op.f('ix_sale_line_transaction_id'), 'sale_line', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_sale_line_upload_id'), 'sale_line', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_line_upload_id'), table_name='sale_line')
    op.drop_index(op.f('ix_sale_line_transaction_id'), table_name='sale_line')
    op.drop_index(op.f('ix_sale_line_store_id'), table_name='sale_line')
    op.drop_index(op.f('ix_sale_line_sku'), table_name='sale_line')
    op.drop_index(op.f('ix_sale_line_date'), table_name='sale_line')
    op.drop_table('sale_line')
    op.drop_index(op.f('ix_product_store_id'), table_name='product')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_bundle_suggestion_store_id'), table_name='bundle_suggestion')
    op.drop_table('bundle_suggestion')
    # ### end Alembic commands ###
